CREATE SCHEMA IF NOT EXISTS billing;

REVOKE ALL ON SCHEMA billing FROM PUBLIC;
REVOKE ALL ON SCHEMA billing FROM anon;
REVOKE ALL ON SCHEMA billing FROM authenticated;
GRANT USAGE ON SCHEMA billing TO service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA billing
  REVOKE ALL ON TABLES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA billing
  REVOKE ALL ON TABLES FROM anon;

ALTER DEFAULT PRIVILEGES IN SCHEMA billing
  REVOKE ALL ON TABLES FROM authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA billing
  GRANT INSERT, SELECT ON TABLES TO service_role;

CREATE OR REPLACE FUNCTION billing.prevent_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'Mutations are not permitted on this billing audit table.';
END;
$$;

CREATE OR REPLACE FUNCTION billing.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;
